export const TableName = {
  CHAT_MESSAGES: 'chat_messages',
  CHAT_ROOMS: 'chat_rooms',
  DISTRICTS: 'districts',
  REGIONS: 'regions',
  USERS: 'users',
  PASSWORD_RESET_TOKENS: 'password_reset_tokens',
  EMAIL_VERIFICATION_TOKENS: 'email_verification_tokens',
  RIDES: 'rides',
  BOOKINGS: 'bookings',
  NOTIFICATIONS: 'notifications',
  VEHICLES: 'vehicles',
  PAYMENTS: 'payments',
  REVIEWS: 'reviews',
  REVIEW_RATINGS: 'review_ratings',
  RIDE_REQUESTS: 'ride_requests',
  RIDE_RULES: 'ride_rules',
} as const;
