export const TableName = {
  DISTRICTS: 'districts',
  REGIONS: 'regions',
  USERS: 'users',
  PASSWORD_RESET_TOKENS: 'password_reset_tokens',
  EMAIL_VERIFICATION_TOKENS: 'email_verification_tokens',
  RIDES: 'rides',
  BOOKINGS: 'bookings',
  CHATS: 'chats',
  NOTIFICATIONS: 'notifications',
  VEHICLES: 'vehicles',
  PAYMENTS: 'payments',
  REVIEW: 'review',
  REVIEW_RATINGS: 'review_ratings',
} as const;
